// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFacturacion.Models.Context;

#nullable disable

namespace SistemaFacturacion.Migrations
{
    [DbContext(typeof(CafeteriaContext))]
    partial class CafeteriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.Empleado", b =>
                {
                    b.Property<string>("cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salario")
                        .HasColumnType("int");

                    b.HasKey("cedula");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            cedula = "4021356164",
                            cargo = "Vendedor",
                            nombre = "Adrian Sarcos",
                            salario = 30000
                        },
                        new
                        {
                            cedula = "402654423",
                            cargo = "Vendedor",
                            nombre = "Valeria Suarez",
                            salario = 30000
                        });
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("empleadocedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("productoid")
                        .HasColumnType("int");

                    b.Property<int>("reservaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("empleadocedula");

                    b.HasIndex("productoid");

                    b.HasIndex("reservaid");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.Reserva", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.Pedido", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.Entities.Empleado", "empleado")
                        .WithMany()
                        .HasForeignKey("empleadocedula");

                    b.HasOne("SistemaFacturacion.Models.Entities.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("productoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion.Models.Entities.Reserva", "reserva")
                        .WithMany()
                        .HasForeignKey("reservaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empleado");

                    b.Navigation("producto");

                    b.Navigation("reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
